version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: local-mongo1
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=TaskListDb
    volumes:
      - mongo-data:/data/db

volumes:
    mongo-data: